default_language_version:
  python: python3

repos:

  # General file linting
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: .patch$
      - id: check-added-large-files
        args: ['--maxkb=4096']
      - id: check-yaml
        args: [--allow-multiple-documents]

  -   repo: https://github.com/psf/black
      rev:  22.6.0
      hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
