name: Deploy to GitHub Pages
on:
  push:
    branches:
      - initial-setup

jobs:
  deploy-docs-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docs
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "./"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/html # The folder the action should deploy.


